# Generated by Django 3.2 on 2024-03-07 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Сумма')),
                ('purpose', models.CharField(choices=[('just', 'Просто деньги'), ('refinancing', 'Рефинансирование кредита'), ('car', 'Новая машина'), ('realestate', 'Недвижимость'), ('mortgage', 'Ипотека')], default='just', max_length=15, verbose_name='Цель кредита')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
