# Generated by Django 4.2.7 on 2024-03-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('no', 'Неодобренна'), ('yes', 'Одобренна')], default='new', max_length=15, verbose_name='Статус'),
        ),
    ]
